import { defineConfig } from 'tsup';

export default defineConfig([
  {
    entry: {
      'core/index': 'src/core/index.ts',
      'react/index': 'src/react/index.ts',
      'mui/index': 'src/mui/index.ts',
      'vite/index': 'src/vite/index.ts',
      'mdx/index': 'src/mdx/index.ts',
      'changelog/index': 'src/changelog/index.ts',
    },
    format: ['esm'],
    dts: true,
    outDir: 'dist',
    external: [
      'react',
      'react-dom',
      '@mui/material',
      '@mui/icons-material',
      '@emotion/react',
      '@emotion/styled',
      '@mdx-js/react',
      'vite',
      'virtual:hotswap-releases',
    ],
    clean: true,
    splitting: true,
  },
  {
    entry: { 'cli/generate-version-json': 'src/cli/generate-version-json.ts' },
    format: ['esm'],
    outDir: 'dist',
    external: ['node:fs', 'node:path', 'node:child_process'],
    banner: { js: '#!/usr/bin/env node' },
    splitting: false,
  },
  {
    entry: { 'cli/hotswap': 'src/cli/hotswap.ts' },
    format: ['esm'],
    outDir: 'dist',
    external: [
      'node:fs',
      'node:path',
      'node:child_process',
      'node:url',
      'commander',
      'magicast',
      'ts-morph',
      'puppeteer',
      'sharp',
    ],
    banner: { js: '#!/usr/bin/env node' },
    splitting: false,
  },
]);
